application: free-counter
version: 0-002
runtime: python
api_version: 1
default_expiration: "1d"

handlers:
- url: /images
  static_dir: static/images

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /
  static_files: static/html/index.html
  upload: static/html/index.html

- url: /graphssss/.*
  script: /graphssss/main.py

- url: /.*
  script: main.py

builtins:
- remote_api: on
- appstats: on

inbound_services:
- warmup
