application: free-counter
version: 0-001
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /
  static_files: static/html/index.html
  upload: static/html/index.html

- url: /.*
  script: main.py

inbound_services:
- warmup


